### PR TITLE
ENH: Use original guidelet base class and register the simulator layo…

### PR DESCRIPTION
**Pull request by cpinter**
…ut externally

This will be the pull request that greatly simplifies the codebase. We need to wait for the SlicerIGT integration of this PR first: https://github.com/SlicerIGT/SlicerIGT/pull/184

### CODE REVIEW

**Comment by cpinter** [comment]
The SlicerIGT PR has been integrated. @carlos-luque can you please test this PR and merge it if works? Thanks!

**Comment by carlos-luque** [comment]
Hello Csaba, 
   
The proposal does not work on the current Guidelet for  Slicer 4.8.1 and Slicer 4.10.0. 
Could you tell me how I can check it?

Thanks

**Comment by cpinter** [comment]
Yes of course it doesn't, as those versions don't have the SlicerIGT that I just updated. You need to either
1. Build latest Slicer and SlicerIGT and guidelet, or
2. Copy the Guidelet base class files referenced in the PR in the installed SlicerIGT extension of 4.10 and then try the updated guidelet. This is kind of a hack, but works

**Comment by carlos-luque** [comment]
I built the 3d Slicer and the modules: SlicerIGT and SlicerOpenIGTLink. I had some difficulties to add the module SlicerOpenIGTLink on the 3d Slicer built. 

I tested the proposal and it worked in various layouts.

**Comment by cpinter** [comment]
Great! Thank you, Carlos!

**Comment by carlos-luque** [comment]
Slicer warns that the Guidelet class doesn´t have the function cleanup().  Was the function removed? I checked the class and the fucntion was renamed to preCleanup(). Is it right?

**Comment by carlos-luque** [comment]
Slicer warns that the Guidelet class doesn´t have the function cleanup(). Was the function removed? I checked the class and the fucntion was renamed to preCleanup(). Is it right?

@cpinter ´s answer

Yes that’s correct. As the scripted loadable module base class has changed so that it has its own cleanup function, using the guidelet function cleanup started to have problems, because it was called too late, when most of the objects were already destroyed. So I renamed it to preCleanup. Andras and Tamas agreed to this, but then it means that we need to change all the cleanup functions to preCleanup in all the guidelets.

**Comment by carlos-luque** [comment]
Hello Csaba
   
  I found two issues in Guidelet class when I was changing the guidelet-based class:

1.  When the fucntion preCleanup is invoked, the phyton generates the following traceback
     The issue is generated when the fucntion setWidget is invoked on a destroyed object. 

Traceback (most recent call last):
  File "D:\B\S410R\Slicer-build\bin\Python\slicer\ScriptedLoadableModule.py", line 104, in _onModuleAboutToBeUnloaded
    self.cleanup()
  File "D:/B/SlicerIGT/lib/Slicer-4.10/qt-scripted-modules\Guidelet\GuideletLoadable.py", line 127, in cleanup
    self.guideletInstance.cleanup()
  File "D:/GTMA/projects/UltrasoundTrainingSystem/UsSimulatorTraining.py", line 96, in cleanup
    Guidelet.preCleanup(self)
  File "D:/B/SlicerIGT/lib/Slicer-4.10/qt-scripted-modules\Guidelet\GuideletLib\Guidelet.py", line 138, in preCleanup
    self.sliceletDockWidget.setWidget(None)
ValueError: Trying to call 'setWidget' on a destroyed QDockWidget object
vtkDebugLeaks has found no leaks.

2.  QLayout: Attempting to add QLayout "" to QFrame "", which already has a layout

Thanks

**Comment by cpinter** [comment]
Hi Carlos,

1. The preCleanup change was supposed to fix just this. I'll look into it.
2. It's only a warning. We get it from all slicelets and guidelets, but it wasn't important enough to spend valuable time to fix it. If it's important for you, your contribution is welcome

csaba

**Comment by cpinter** [comment]
Oh wait.

1. It seems you didn't update all the classes. The cleanup function shouldn't exist in GuideletLoadable. The problem seems to be on your side

**Comment by carlos-luque** [comment]
Hello Csaba, 
   
   I have the latter version of the SlicerIGT. The file GuideletLoadable has the function cleanup (line 122).
 if the warning is all slicelets and guidelets, it is not important for me right now. 

Best regards, 
Carlos Luque

**Comment by cpinter** [comment]
Maybe I missed one call. I'll check.

**Comment by cpinter** [comment]
I just noticed that al this emailing went to GitHub. The easiest way to differentiate between real emails and email notifications of GitHub messages is the presense or absence of letter format, i.e. greeting and signature. Now I updated the messages and removed the previous emails from them. But in the future please don't include these email-specific things in the comments and I'll know it's not only for me. Thanks!

**Comment by cpinter** [comment]
The problem is that your cleanup-preCleanup fix was not completely correct. Instead of this
https://github.com/mt4sd/UltrasoundTrainingSystem/commit/6500619243707ae597793425d8dfbda0212d2298
you need a bit more, see
https://github.com/SlicerIGT/ExampleGuideletExtension/commit/efe4f3663e214f47ef16421bc5652041b259dc70

It's because the way you did the change the scripted loadable module will still call the preCleanup function at the wrong time: when the module is unloaded, but that is too late. Instead, you need to call a preCleanup function in the __del__ function at the time of destruction of the instance.

**Comment by carlos-luque** [comment]
I did it you´d suggested, but I have another issue. 

Traceback (most recent call last):
  File "D:\B\S410R\Slicer-build\bin\Python\slicer\ScriptedLoadableModule.py", line 104, in _onModuleAboutToBeUnloaded
    self.cleanup()
  File "D:/B/SlicerIGT/lib/Slicer-4.10/qt-scripted-modules\Guidelet\GuideletLoadable.py", line 127, in cleanup
    self.guideletInstance.cleanup()
AttributeError: 'UsSimulatorTrainingGuidelet' object has no attribute 'cleanup'

It´s due to the function cleanup() in GuideletLoadable.py invokes the cleanup() in GuideletInstance. So, the function cleanup() is necessary for GuideletLoadable.  Is the GuideletLoadable.py different ?

I checked the ExampleGuideletGuidelet and I have the same issue

Traceback (most recent call last):
  File "D:\B\S410R\Slicer-build\bin\Python\slicer\ScriptedLoadableModule.py", line 104, in _onModuleAboutToBeUnloaded
    self.cleanup()
  File "D:/B/SlicerIGT/lib/Slicer-4.10/qt-scripted-modules\Guidelet\GuideletLoadable.py", line 127, in cleanup
    self.guideletInstance.cleanup()
AttributeError: 'ExampleGuideletGuidelet' object has no attribute 'cleanup'

**Comment by cpinter** [comment]
Yes I saw it but wasn't sure it will be a problem. I think I need to rename it in the GuideletLoadable class as well. I'll check soon.

This is only a problem at exiting right?

**Comment by carlos-luque** [comment]
I changed the function in GuideletLoadable and the issue was fixed. However, there is another issue as I commented in the first message about the setWidget is called on a destroyed QDockWidget object.
Has this issue generated before the Guidelet class was changed?

Traceback (most recent call last):
  File "D:\B\S410R\Slicer-build\bin\Python\slicer\ScriptedLoadableModule.py", line 104, in _onModuleAboutToBeUnloaded
    self.cleanup()
  File "D:/B/SlicerIGT/lib/Slicer-4.10/qt-scripted-modules\Guidelet\GuideletLoadable.py", line 127, in cleanup
    self.guideletInstance.preCleanup()
  File "D:/GTMA/projects/UltrasoundTrainingSystem/UsSimulatorTraining.py", line 96, in preCleanup
    Guidelet.preCleanup(self)
  File "D:/B/SlicerIGT/lib/Slicer-4.10/qt-scripted-modules\Guidelet\GuideletLib\Guidelet.py", line 138, in preCleanup
    self.sliceletDockWidget.setWidget(None)
ValueError: Trying to call 'setWidget' on a destroyed QDockWidget object

**Comment by cpinter** [comment]
Carlos, again this is the same problem: the scripted loadable module base class calls the cleanup function, which, if calls these functions that do unsetting or disconnecting when every object is already destroyed, will fail. Please either take time to understand the problem and then trying to fix it, or wait a bit until I can get there and do it myself.

**Comment by carlos-luque** [comment]
Csaba, 

 I did it you commented to test if they could fix the issue. and I only informed you the outcomes. After that, we should study the reason and look for a solution. 
I see you know the principal reason.  I will try to fix it.

**Comment by cpinter** [comment]
Has development of this guidelet stop?

I was just checking the issue we talked about, and noticed that the small error in the UsSimulatorTraining code was also not fixed. I'm talking about this one:

> The problem is that your cleanup-preCleanup fix was not completely correct. Instead of this
6500619
you need a bit more, see
SlicerIGT/ExampleGuideletExtension@efe4f36

Is this still of interest?

**Comment by cpinter** [comment]
Although I didn't try to reproduce the original error, I made fixes in the GuideletLib class, and that, together with the change in this guidelet I'm referring to just above, result in no error messages when exiting. Let me know if you want to get this integrated.

**Comment by carlos-luque** [comment]
We´re working the project, but we have to finish the urgent things and we're thinking about other the i18n and l10n proposals. 
I've just committed the recent changes. 

Of course!!. What changes have you done in GuideletLib class?

**Comment by cpinter** [comment]
Just two things:

* Rename cleanup to preCleanup so that it doesn't get called at the wrong time as the others were (this I believe is the last place where it was still like that)
* Add a hideEvent function that calls preCleanup at the right time

So I don't get any errors when exiting which is good :)

If you could just do the following in the main branch before starting any integration so that it doesn't get lost that would be great:
* Rename cleanup function itself to preCleanup ("def preCleanup(self):")
* In the __del__ function call preCleanup instead of cleanup

And then this issue is fully solved. I still need to commit this change in SlicerIGT but I'll do it right now.
Thanks!!

**Comment by cpinter** [comment]
Done, this is it:
https://github.com/SlicerIGT/SlicerIGT/commit/8847aec7841baeefe40598929c7c797781b170de

**Comment by carlos-luque** [comment]
Thanks so much.
I´ll change the code according to your comments. After that, I inform you of it.

**Comment by carlos-luque** [comment]
I have just tested the changes, and there wasn't any message when the Guidelet had closed. 
I tested the Guidelet 'UltrasoundTrainingSystem ' without the fucntion 'hideEvent'. The message is not showed after the guidelet was closed.  When is the function 'hideEvent' invoked?

**Comment by cpinter** [comment]
When the window disappears, which is a relatively early stage of exiting.

**Comment by carlos-luque** [comment]
If the function is defined in the class GuideletWidget which calls the function preCleanup from guidelet instance (For example: UsSimulatorTrainingGuidelet class), I don't think the function hideEvent need to be defined in the class UsSimulatorTrainingGuidelet. Is it right?

**Comment by cpinter** [comment]
It's way deeper, in Qt. That's right, it shouldn't be needed on that level. Just the two things I wrote before:

* Rename cleanup function itself to preCleanup ("`def preCleanup(self):`")
* In the `__del__` function call preCleanup instead of cleanup

**Comment by carlos-luque** [comment]
Great!!. Those changes were committed two days ago.

**Comment by cpinter** [comment]
Exellent! We're all set then. Let me know if you need further things related to this or something else.
Happy holidays :)

**Comment by carlos-luque** [comment]
Ok.
My holiday starts on 22nd December. Thanks and happy Holidays.

**Pull request merged**
